CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [FirstName] NVARCHAR(50) NOT NULL, 
    [LastName] NVARCHAR(50) NULL, 
    [EmailAddress] NVARCHAR(100) NOT NULL, 
    [UserName] NVARCHAR(50) NOT NULL UNIQUE, 
    [Password] NVARCHAR(100) NOT NULL, 
    [Salt] NVARCHAR(50) NOT NULL
)
